---
SIZES:
  - 100
  - 300
  - 800
  - 1000
  - 2000

CRITICALSIZES:
  - width: 220
    height: 480
  - width: 1366
    height: 768

SCRAPPEREXTRACT: False
SCRAPPERLINK: ""
GENIMAGESIZES: False
GENCRITICAL: False
BUILDBUNDLE: True
BROWSERSYNC:
  tunnel: False
  directory: True
MINIFYHTMLOPTIONS:
  collapseWhitespace: False
  preserveLineBreaks: False